# File: .github/workflows/add-widget-state.yml

name: Inject Widget State Metadata

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  inject-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Add empty `state` if missing in widget-state mime
        shell: bash
        run: |
          updated=false
          for nb in $(git ls-files '*.ipynb'); do
            tmp=$(mktemp)
            jq '
              if .metadata.widgets
                 and .metadata.widgets["application/vnd.jupyter.widget-state+json"]
              then
                .metadata.widgets["application/vnd.jupyter.widget-state+json"].state
                |= . // {}
              else
                .
              end
            ' "$nb" > "$tmp"
            if ! diff -q "$nb" "$tmp" >/dev/null; then
              mv "$tmp" "$nb"
              echo "✅ Patched $nb"
              updated=true
            else
              rm "$tmp"
            fi
          done
          if [ "$updated" = false ]; then
            echo "ℹ️  All notebooks already have a widget-state ‘state’ key."
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: inject widget state metadata" && git push)
