# File: .github/workflows/add-widget-state.yml

name: Embed Jupyter Widget State

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  embed-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbformat & nbconvert
        run: python -m pip install nbformat nbconvert

      - name: Embed widget-state in all notebooks
        shell: bash
        run: |
          python - << 'PYCODE'
          import os
          import nbformat
          from nbconvert.preprocessors import WidgetStatePreprocessor

          preprocessor = WidgetStatePreprocessor()

          for root, _, files in os.walk('.'):
              for fname in files:
                  if not fname.lower().endswith('.ipynb'):
                      continue
                  path = os.path.join(root, fname)
                  nb = nbformat.read(path, as_version=4)

                  try:
                      nb, _ = preprocessor.preprocess(nb, {'metadata': {}})
                  except Exception as e:
                      print(f"❗ Failed to embed in {path}: {e}")
                      continue

                  nbformat.write(nb, path)
                  print(f"✅ Embedded widget state in {path}")
          PYCODE

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: embed Jupyter widget state" && git push)
