# File: .github/workflows/add-widget-state.yml

name: Add Widget State to Notebooks

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  add-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbformat
        run: python -m pip install nbformat

      - name: Add widget state metadata
        shell: bash
        run: |
          python - << 'PYCODE'
          import os
          import nbformat

          WIDGET_MIME = 'application/vnd.jupyter.widget-state+json'

          def ensure_state(block):
              """
              If WIDGET_MIME is present in block, ensure it has a 'state' key.
              Return True if we inserted one.
              """
              if WIDGET_MIME in block:
                  widget_meta = block[WIDGET_MIME]
                  if 'state' not in widget_meta:
                      widget_meta['state'] = {}
                      return True
              return False

          any_updated = False
          for root, _, files in os.walk('.'):
              for fname in files:
                  if not fname.lower().endswith('.ipynb'):
                      continue
                  path = os.path.join(root, fname)
                  nb = nbformat.read(path, as_version=4)
                  updated = False

                  # Top-level metadata
                  if 'widgets' in nb.metadata:
                      if ensure_state(nb.metadata['widgets']):
                          updated = True

                  # Per-cell metadata
                  for cell in nb.cells:
                      if 'widgets' in cell.metadata:
                          if ensure_state(cell.metadata['widgets']):
                              updated = True

                  if updated:
                      nbformat.write(nb, path)
                      print(f'✅ Added state to widgets in {path}')
                      any_updated = True

          if not any_updated:
              print('ℹ️  All notebooks already contain widget state.')
          PYCODE

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: add widget state metadata" && git push)
