# File: .github/workflows/add-widget-state.yml

name: Embed Widget State via Execution

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  embed-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python & ipywidgets
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install nbformat nbclient nbconvert ipywidgets

      - name: Re-execute notebooks to capture widget state
        shell: bash
        run: |
          python - << 'PYCODE'
          import os
          import nbformat
          from nbconvert.preprocessors import ExecutePreprocessor

          ep = ExecutePreprocessor(
              timeout=600,
              kernel_name='python3',
              store_widget_state=True  # <-- embed widget state in metadata
          )

          updated = False
          for root, _, files in os.walk('.'):
              for f in files:
                  if not f.lower().endswith('.ipynb'):
                      continue
                  path = os.path.join(root, f)
                  nb = nbformat.read(path, as_version=4)
                  try:
                      # run all cells and capture widget state
                      ep.preprocess(nb, {'metadata': {'path': os.path.dirname(path) or '.'}})
                  except Exception as e:
                      print(f"❗ Skipping {path}: execution failed ({e})")
                      continue

                  nbformat.write(nb, path)
                  print(f"✅ Embedded widget state in {path}")
                  updated = True

          if not updated:
              print("ℹ️  No notebooks were executed (or none needed widget-state).")
          PYCODE

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: embed Jupyter widget state" && git push)
