# File: .github/workflows/add-widget-state.yml

name: Inject Widget State Metadata

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  inject-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Add empty `state` if missing in widget-state mime (with JSON validation)
        shell: bash
        run: |
          patched_any=false

          for nb in $(git ls-files '*.ipynb'); do
            tmp=$(mktemp)

            # Try to patch
            jq '
              if .metadata.widgets
                 and .metadata.widgets["application/vnd.jupyter.widget-state+json"]
              then
                .metadata.widgets["application/vnd.jupyter.widget-state+json"].state
                |= . // {}
              else
                .
              end
            ' "$nb" > "$tmp" 2>/dev/null

            # First, did jq even produce valid JSON?
            if ! jq empty "$tmp" >/dev/null 2>&1; then
              echo "❗ JSON invalid after patch attempt, skipping: $nb"
              rm "$tmp"
              continue
            fi

            # Next, did anything actually change?
            if ! diff -q "$nb" "$tmp" >/dev/null; then
              mv "$tmp" "$nb"
              echo "✅ Patched widget-state in $nb"
              patched_any=true
            else
              rm "$tmp"
            fi
          done

          if [ "$patched_any" = false ]; then
            echo "ℹ️  No notebooks needed patching (or JSON errors prevented changes)."
          fi

      - name: Commit any changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: inject widget state metadata" && git push)
