name: Clean Jupyter Notebooks Metadata

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  strip-widgets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbformat
        run: pip install nbformat

      - name: Strip widget metadata
        run: |
          python - << 'EOF'
import nbformat, os
for root, _, files in os.walk('.'):
    for fname in files:
        if fname.endswith('.ipynb'):
            path = os.path.join(root, fname)
            nb = nbformat.read(path, as_version=4)
            nb.metadata.pop('widgets', None)
            for cell in nb.cells:
                cell.metadata.pop('widgets', None)
            nbformat.write(nb, path)
EOF

      - name: Commit cleaned notebooks
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '**/*.ipynb'
          git diff --quiet && echo "No changes to commit." || (git commit -m "chore: strip widget metadata" && git push)
