# File: .github/workflows/restore-notebook-widgets.yml

name: Embed Jupyter Widget State

# give GITHUB_TOKEN permission to push
permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  embed-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install nbformat nbclient ipywidgets

      - name: Execute notebooks and embed widget state
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --ExecutePreprocessor.store_widget_state=True \
            --ExecutePreprocessor.allow_errors=True \
            --inplace \
            **/*.ipynb

      - name: Commit notebooks with widget state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet --exit-code \
            || (git commit -am "chore: embed widget state in notebooks" && git push)
