# File: .github/workflows/embed-widget-state.yml

name: Embed Jupyter Widget State via nbclient

# Grant push permissions so we can commit back changes
permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  embed-widget-state:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute notebooks & embed widget state
        # Merge install + execute into one bash block to keep YAML simple
        shell: bash
        run: |
          # 1) Install needed libraries
          pip install nbformat nbclient ipywidgets

          # 2) Re-run each notebook, capturing widget state
          python - <<EOF
          import glob
          import nbformat
          from nbclient import NotebookClient

          for path in glob.glob("**/*.ipynb", recursive=True):
              nb = nbformat.read(path, as_version=4)
              client = NotebookClient(
                  nb,
                  allow_errors=True,
                  store_widget_state=True,
                  timeout=None
              )
              try:
                  client.execute()
              except Exception as e:
                  print(f"⚠️ Execution failed for {path}: {e}")
              nbformat.write(nb, path)
          EOF

      - name: Commit notebooks with widget state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # If any notebooks changed, commit & push them
          git diff --quiet --exit-code \
            || (git commit -am "chore: embed widget state in notebooks" && git push)
